name: 'NDPA Compliance Scan'
description: 'Audits IaC and Kubernetes manifests against the Nigeria Data Protection Act 2023.'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  target:
    description: 'Path to file or directory to scan'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Download ndepa-scan Binary
      shell: bash
      run: |
        VERSION="1.1.0"
        curl -sSL "https://github.com/bolanuga-dev/ndepa-scan/releases/download/v${VERSION}/ndepa-scan_${VERSION}_linux_amd64.tar.gz" -o ndepa-scan.tar.gz
        tar -xzf ndepa-scan.tar.gz
        chmod +x ndepa-scan
        sudo mv ndepa-scan /usr/local/bin/

    - name: Run NDPA Compliance Scan
      shell: bash
      run: |
        ndepa-scan ${{ inputs.target }}
